---
title: "OkCupid"
output:
  html_document:
    df_print: paged

```{r}
library(data.table)
library(stringr)
library(ggplot2)
library(dplyr)
library(mice)
library(tidyr)
library(mice)
library(tidytext)

#Datacleaning OK Cupid----First Import and replace blanks with "NA" and "-1" in Income category with "NA"
Data<-read.csv('profiles.csv', na.strings =c("","-1"))

#remove all essays but essay 5 "The six things I could never do without"
Data$essay0<-NULL
Data$essay1<-NULL
Data$essay2<-NULL
Data$essay3<-NULL
Data$essay4<-NULL
Data$essay6<-NULL
Data$essay7<-NULL
Data$essay8<-NULL
Data$essay9<-NULL
#remove variable "last online" information is NA to analysis
Data$last_online<-NULL

#remove rows with more than 7 (50% of optional responses) missing values using manual function 'delete.na'. 
delete.na <- function(DF, n=0) {
  DF[rowSums(is.na(DF)) <= n,]
}

#59K before 
Data<-delete.na(Data, 7)
#56K Observations remaining 

#determine amount of missing values for each category 

sort(sapply(Data, function(x) { 
  sum(is.na(x)) }), decreasing=TRUE)

#variables with missing values greater than 30% of observations are removed from analysis. 
#This includes "income", "offspring", and "Diet

Data$income<-NULL
Data$offspring<-NULL
Data$diet<-NULL

#18 variables remain

#cleaning data / formatting 
#replace "&rsquo;" in sign" category with "'"

Data$sign<-str_replace_all(Data$sign,"&rsquo;","'")

#replace "<<br/>" in essay 5 with " " 
Data$essay5<-str_replace_all(Data$essay5,"<br />"," ")


#Make a Backup of Data before moving on with analysis 
Data_Backup<-Data

#review data structure
str(Data)

#update height to numeric category..Factor Variable Trap, must convert to character first 
Data$height<-as.numeric(as.character(Data$height))

#view height and age summarys
summary(Data$height)
summary(Data$age)
#identify and remove outliers for height and age 
sum(Data$height<50)
sum(Data$age>65)

#remove rows with outliers for height and age. 


#remove rows with missing education data for analysis. 
Data<-Data[!is.na(Data$education),]
#left with 51K observations 

#imputate missing values for Drinks, Drugs, and Smoking
imp_data<-mice(Data[,4:5])

#run MICE for missing data for Drinks, Drugs, and Smoking

```
```{r}
men.only <-
    Data %>%
    filter(sex == 'm')
women.only <-
    Data %>%
    filter(sex == 'f')

#tolower() changes all the letters to lowercase so ThiS and this are counted as one word
#strsplit() splits the string into individual strings be
#table() counts the frequency of each word
men.word.count <-
    data.frame(table(unlist(strsplit(tolower(men.only$essay5), " "))))
women.word.count <-
    data.frame(table(unlist(strsplit(tolower(women.only$essay5), " "))))

men.word.count %>%
    arrange(-Freq)

women.word.count %>%
    arrange(-Freq) 

men.word.count <- data.frame(table(unlist(strsplit(tolower(men.only$essay5), " "))))
#Renamed Var1 to Word because it was easier to understand structure using "Word"
colnames(men.word.count)[1] <- 'Word'
#gsub is a part of the stringr package. In this case, it's used to replace special characters in the set of strings. 
#[\n] is a line break, while [-], [[:punct:]], [0-9] are other special characters like punctuation and numerical digits. 
men.word.count$Word <- gsub("[\n]", "", men.word.count$Word)
men.word.count$Word <- gsub("-", "", men.word.count$Word)
men.word.count$Word <- gsub("[[:punct:]]", "", men.word.count$Word)
men.word.count$Word <- gsub("[0-9]", "", men.word.count$Word)
#Input cleaned words into new word count data frame
men.word.count <- men.word.count[men.word.count$Word != '', ]


ggplot(men.word.table, aes(x = Word, y = Freq, fill= Word))+ geom_bar(stat = "identity")+labs(x = "Word", y = "How Frequently Word is Used", title ="Most Popular Words in Male OkCupid Profiles (Essay #5)")
```


```{r}
women.word.count <- data.frame(table(unlist(strsplit(tolower(women.only$essay5), " "))))
colnames(women.word.count)[1] <- 'Word'
women.word.count$Word <- gsub("[\n]", "", women.word.count$Word)
women.word.count$Word <- gsub("-", "", women.word.count$Word)
women.word.count$Word <- gsub("[[:punct:]]", "", women.word.count$Word)
women.word.count$Word <- gsub("[0-9]", "", women.word.count$Word)
women.word.count <- women.word.count[women.word.count$Word != '', ]


ggplot(women.word.table, aes(x = Word, y = Freq, fill= Word))+ geom_bar(stat = "identity")+labs(x = "Word", y = "How Frequently Word is Used", title ="Most Popular Words in Female OkCupid Profiles (Essay #5)")


```

```{r}
ggplot(Data, aes(x = sex, color = sex, fill = sex, alpha = 0.2)) +
geom_density() + ggtitle("Density plot of sex")

ggplot(Data, aes(x = age, fill = sex)) +
   geom_bar() 
```



```{r}
women.word.count <- data.frame(table(unlist(strsplit(tolower(women.only$essay5), " "))))
colnames(women.word.count)[1] <- 'Word'
women.word.count$Word <- gsub("[\n]", "", women.word.count$Word)
women.word.count$Word <- gsub("-", "", women.word.count$Word)
women.word.count$Word <- gsub("[[:punct:]]", "", women.word.count$Word)
women.word.count$Word <- gsub("[0-9]", "", women.word.count$Word)
women.word.count <- women.word.count[women.word.count$Word != '', ]

women.word.table<-women.word.count %>%
filter(!(Word %in% stop_words$word)) %>%
arrange(-Freq) %>%
  


ggplot(women.word.table, aes(x = Word, y = Freq, fill= Word))+ geom_bar(stat = "identity")+labs(x = "Word", y = "How Frequently Word is Used", title ="Most Popular Words in Female OkCupid Profiles (Essay #5)")
```

